> ### **Numpy Array Operation** 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.


# Let's Learn Numpy- Numpy for Beginners


Functions Used:

- function 1: np.array
- function 2: np.concatenate
- function 3: np.ones 
- function 4: np.mutmal
- function 5: np.eyes

In [9]:
!pip install jovian --upgrade -q

In [10]:
import jovian

<IPython.core.display.Javascript object>

In [11]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Uploading notebook to https://jovian.ai/a-malhotraakash/numpy-array-operations


<IPython.core.display.Javascript object>

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [3]:
# List of functions explained 
function1 = np.array
function2 = np.concatenate
function3 = np.ones
function4 = np.matmul
function5 = np.eye

## Function 1 - np.array

This function creates an (n-dimensional) array out of a normal python list.

In [4]:
np.array([[5,10,15,20],[3,6,9,12]])

array([[ 5, 10, 15, 20],
       [ 3,  6,  9, 12]])

A 2-d array out of a nested list.

In [5]:
np.array([[1,2,3,4,5],[6,7,8,9,10.0]])

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

Upcasting : When a single element of the array is of float type than all the elements are upcasted to float type.

In [7]:
np.array([[1,2,3],[4,5]])

array([list([1, 2, 3]), list([4, 5])], dtype=object)

Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If we still wanted to make an array we should assign dtype=object

A numpy array has obvious advantages over a normal python list.

In [12]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ai/a-malhotraakash/numpy-array-operations


<IPython.core.display.Javascript object>

## Function 2 - np.concatenate

This function joins a sequence of arrays along an existing axis.

In [13]:
# Example 1 - working
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Concatenating two arrays along axis=1

In [14]:
# Example 2 - working
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

Concatenating two arrays when axis=None. If axis is None, arrays are flattened before use.

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

Since, the array along dimensioon 1 index 0 has 2 elements and the array along index 1 has size 3. All the input array dimensions for the concatenation axis must match exactly.

It is a useful function to join 2 functions.

In [16]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ai/a-malhotraakash/numpy-array-operations


<IPython.core.display.Javascript object>

## Function 3 - np.ones

This function returns a new array of given shape and type, filled with ones.

In [48]:
# Example 1 - working
np.ones(5,dtype=int)

1-d array

In [49]:
# Example 2 - working
np.ones((2,3))

2-d array with floating point.

In [50]:
# Example 3 - breaking (to illustrate when it breaks)
np.ones(3,4)

TypeError: Cannot interpret '4' as a data type

Shape of the array should be provided within parantheses.

It is used to form an identity matrix.

In [57]:
jovian.commit()

## Function 4 - np.matmul

This function returns matrix product of two arrays.

In [58]:
# Example 1 - working
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

Matrix Multiplication of two 2-d arrays.

In [59]:
# Example 2 - working
a = np.array([[1, 0],
              [0, 1]])
b = np.array([1, 2])
np.matmul(a, b)

np.matmul(b, a)

The matmul function implements the semantics of the @ operator introduced in Python 3.5

In [60]:
# Example 3 - breaking (to illustrate when it breaks)
np.matmul([1,2], 3)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

Scalar multiplication raises an error.

This function is useful for matrix multiplication of two matrices or vectors.

In [61]:
jovian.commit(project='numpy-array-operations')

## Function 5 - np.eye

This function returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [62]:
# Example 1 - working
np.eye(5)

Creates a 5-d diagonal matrix.

In [63]:
# Example 2 - working
np.eye(3,5,dtype=int)

Creates a 3x5 array with int type elements.

In [64]:
# Example 3 - breaking (to illustrate when it breaks)
np.eye(2,3.5,dtype=float)

TypeError: 'float' object cannot be interpreted as an integer

A matrix can't have a floating point dimension.

np.eye is , generally, used to form a diagonal matrix.

In [65]:
jovian.commit(project='numpy-array-operations')

Conclusion
We covered 5 interesting functions from the NumPy library, namely,

np.array
np.concatenate
np.ones
np.matmul
np.eye
Since I'm not a good teacher so, I didnt covered each topic exhaustively. There are many resources out there to refer to for more depth understanding. If you want to dig deep, check out the Resources & References section below.



## Reference Links
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...